import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter()
  const handleClick = () => {
    console.log('placing your oredr');
    setTimeout(() => {
      router.push('/product')
    }, 5000);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>HOME PAGE</div>
      <Link href={"/blog"}>
        <a>Blog</a>
      </Link>
      <br />
      <Link href={"/product"}>
        <a>Product</a>
      </Link>
      <br/>
      <button onClick={handleClick}>
        place order
      </button>
      <br />
      <Link href={"/posts"}>
        <a>posts</a>
      </Link>
    </div>
  );
}
